### ISSUE TITLE
你的wakatime action构建出现的报错，导致近段时间都没有更新成功

### ISSUE THREAD

**Issue by minibear2333** [tw93/tw93#1]
![image](https://user-images.githubusercontent.com/42294819/88499581-df18b980-cff8-11ea-895d-474a6b127f54.png)

详情见
https://github.com/tw93/waka-box/runs/912686070?check_suite_focus=true

**Comment by tw93** [comment]
看了下是waka的 api 挂了，我本地 vscode 也出现这个问题，等待他们修复就好

**Comment by minibear2333** [comment]
wakatime  会偷偷上传/盗取代码吗？
