### ISSUE TITLE
wakatime 会偷偷上传/盗取代码吗？

### ISSUE THREAD

**Issue by minibear2333** [tw93/tw93#2]

**Comment by tw93** [comment]
在官网找到了这个：https://wakatime.com/faq#data-collected
可供参考，一般这种工具偷偷上传代码早就被发现了，同时国外这种公司数据隐私还是挺重要的

What data is sent to your servers? 
WakaTime sends heartbeat events triggered from user actions inside your text editor to the WakaTime API.

Heartbeat events contain data such as:

path of the currently opened file, website, or app
project names
branch names
editor names, for example ‘Vim’ or ‘VS Code’
languages, for example ‘Python’ or ‘JavaScript’
libraries/imports used, for example ‘Django’ or ‘Rails’
line counts of opened files
position of your cursor in opened files
your computer’s hostname, like ‘MacbookPro.local’ or ‘HOME-PC’
category, for example ‘Debugging’, ‘Building’, or ‘Coding’
your computer’s operating system name
your computer’s timezone
…and of course, timestamps
Heartbeat events are sent:

every 2 minutes if you are actively using your text editor
when you switch between files
every time you write to a file

**Comment by minibear2333** [comment]
感谢,因为这个东西把项目和所有使用过的文件名都获取到了，比较担心
