### ISSUE TITLE
Perf: Trend Weekly 信息流更新停留在2023-09-10了咧

### ISSUE THREAD

**Issue by Trojan0523** [tw93/tw93#4]
- 如题～ 是 Actions 的 workflow 失效了么，貌似每天都还在跑
- ScreenShot In Oct.9, 2023
<img width="916" alt="image" src="https://github.com/tw93/tw93/assets/44562268/32e39919-9b44-43a7-8c45-da7f5abc863b">

**Comment by tw93** [comment]
谢谢反馈 我去看看

**Comment by tw93** [comment]
已经更新，python 依赖的 httpx 的版本问题导致，已经修复
